version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":seedling:"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"

  # Enable version updates for Go tools
  - package-ecosystem: "gomod"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"

  - package-ecosystem: "docker"
    directory: "/hack/tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":seedling:"
