apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen

resources:
- ../config/default

images:
- name: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller
  newName: registry.ci.openshift.org/openshift
  newTag: aws-cluster-api-controllers

patches:

# Remove unsubstituted annotation from ServiceAccount
- target:
    kind: ServiceAccount
    name: capa-controller-manager
  patch: |-
    - op: remove
      path: /metadata/annotations/${AWS_CONTROLLER_IAM_ROLE~1#arn~1eks.amazonaws.com~1role-arn

# Add TLS configuration args (substituted by cluster-capi-operator revisiongenerator)
- target:
    kind: Deployment
    name: capa-controller-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls-min-version=${TLS_MIN_VERSION}"
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--tls-cipher-suites=${TLS_CIPHER_SUITES}"
