apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: capa-validating-webhook-configuration
webhooks:
- name: validation.awsmachinepool.infrastructure.cluster.x-k8s.io
  $patch: delete
